Traceback (most recent call last):
  File "/users/acc22xl/llama_adversarial_classification/scripts/classify_adversarial.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
